### PR TITLE
LPS-71463 Add test

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@vicnate5 I've changed the way we add validation for a field type (Text, Numeric). I think we need to update Poshi. Can you confirm that? Thanks!

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Pull request closed without merging**
