### PR TITLE
[Technical Support] LPS-76812 Links in email notifications coming from Forms are pointing to localhost

### PR DESCRIPTION
**Pull request by natocesarrego**
Hey Forms team,

I'm forwarding another pull already reviewed. Link to CI results [here](https://github.com/natocesarrego/com-liferay-dynamic-data-mapping/pull/5#issuecomment-355909839).

Thanks in advance.

@IstvanD

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Sent to https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/664

**Comment by natocesarrego** [comment]
Hey @pedroqueiroz94 and @leoadb,

I believe that you guys are already aware of the reasons which have motivated the disable of automatic CI execution and, considering these reasons, I've added to this pull a link to the CI result of the pull request sent to me, because I've thought you guys would use it and save time/CI resources.

Therefore, do you guys think that is still necessary execute the CI even without any modification from your side?

I'm asking this in order to understand your current review process and also organize myself to be aligned with it.

Thanks in advance.

**Pull request closed without merging**
