### PR TITLE
LPS-75038

### PR DESCRIPTION
**Pull request by dustinryerson**
https://issues.liferay.com/browse/LPS-75038

/cc @gregory-bretall

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by interaminense** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by interaminense** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
resent and merged at https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/437.

Thx @gregory-bretall and @dustinryerson

**Pull request closed without merging**
