### PR TITLE
LPS-77034 setting default currentTab to 'forms'

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by linolaoj** [comment]
Hi, going to resend to liferay-portal.

**Comment by linolaoj** [comment]
Here it is https://github.com/rafaprax/liferay-portal/pull/251

**Comment by rafaprax** [comment]
ci:retest

**Pull request closed without merging**
