### PR TITLE
LPS-75159 Build lang

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by rodrigo-e-c-souza** [comment]
@leoadb this failure is not related to the PR, we are waiting for the fix.

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by rodrigo-e-c-souza** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
@leoadb @rafaprax this is **finally** good to go!!!

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
resent at https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/705

**Pull request closed without merging**
