### PR TITLE
LPS-76085

### PR DESCRIPTION
**Pull request by jonathanmccann**
Related to https://github.com/jonmak08/liferay-portal/pull/1805

/cc @fortunatomaldonado

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by rafaprax** [comment]
Hey @pedroqueiroz94 
Could you please review this pr? Thx dude :)

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
PR submitted to https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/560. Please, check changes. :) 

@jonathanmccann 
@fortunatomaldonado

**Comment by pedroqueiroz94** [comment]
ci:close

**Pull request closed without merging**
