### PR TITLE
LPS-74303 Uses new classes in asset service module

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Sent on https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/407

**Pull request closed without merging**
