### PR TITLE
LPS-75425 Get scopeGroupId from ThemeDisplay in case it does not come directly inside the Request

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
hey guys, the test failure here is due to flakiness in an unrelated component. The fix is in progress here https://issues.liferay.com/browse/LRQA-35982

**Comment by rafaprax** [comment]
Thx @vicnate5

**Pull request merged**
