### PR TITLE
LPS-75844 Fix error message color by changing css class to form-feedback-item

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by alinedoleron** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by vicnate5** [comment]
@rafaprax Failures here are strange. Form fails to save with JDBC batch update failure. Rodrigo and I will continue to monitor now that this is merged.

**Pull request merged**
