### PR TITLE
LPS-77168

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
@inacionery , can you take a look at this? thanks!

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
forward to https://github.com/inacionery/liferay-portal/pull/140

**Comment by rafaprax** [comment]
ci:close

**Pull request closed without merging**
