### PR TITLE
LPS-73070

### PR DESCRIPTION
**Pull request by Ithildir**
cc @jbalsas

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
ci:retest

**Comment by vicnate5** [comment]
@leoadb This should fix a build failure we are seeing at head when building locally.

**Comment by vicnate5** [comment]
Test failures are OK. They are known issues not related to this pull.

**Comment by jpince** [comment]
@leoadb thank you!

**Pull request merged**
