### PR TITLE
LPS-56589

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by daviddotzhang** [comment]
Hi@leoadb 

are the fixes has been merged into liferay-portal -> master ?
as far as I have checked, only three of the fixes commits are merged into liferay-portal ?

**Comment by daviddotzhang** [comment]
addtional,  I also found 942e06d4e72ef9135496b4cf560312721db91caf  "LPS-56589 - Update upgrade" , is also added,  is it intented ?

**Comment by leoadb** [comment]
@daviddotzhang The first two commits were already merged a couple of days ago. You can check the history. Thanks!

**Comment by leoadb** [comment]
@daviddotzhang Please refer to https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/211

**Comment by daviddotzhang** [comment]
@leoadb could you let me know when the following commits will be synced to https://github.com/liferay/liferay-portal ?
LPS-56589 - Specify schema version			5522e8e
LPS-56589 - Create upgrade steps			e59c39a
LPS-56589 - Update upgrade steps registrator

**Pull request merged**
