### PR TITLE
LPS-63227 Update build.gradle to 1.8 compat

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@ctampoya @vicnate5 can we update these tests? I've changed the password field to be type=password on this pull.

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRQA-33520

**Comment by vicnate5** [comment]
Test Fix: https://github.com/brianchandotcom/liferay-portal/pull/49936

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
@marcellustavares This didn't rebased to head yet, go ahead and run a re-test tomorrow morning and it should be good.

**Comment by rafaprax** [comment]
ci:retest

**Comment by vicnate5** [comment]
Master was broken at head, it is fixed now.

ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:stop

**Pull request merged**
