### PR TITLE
LPS-71909 remove required for validation before submit

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Sent at https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/289

**Pull request closed without merging**
