### PR TITLE
LPS-70052

### PR DESCRIPTION
**Pull request by matethurzo**
need to revert this, as the SB template changes caused breaking changes in 7.0.x

### CODE REVIEW

**Comment by matethurzo** [comment]
the failure is unrelated to my changes

**Comment by marcellustavares** [comment]
Thanks @matethurzo, SF issue fix in other pull. I'll retest this once it's merged.

**Comment by leoadb** [comment]
ci:retest

**Comment by matethurzo** [comment]
thanks @marcellustavares @leoadb

**Pull request merged**
