### PR TITLE
LPS-75357 Change the hover event to open the sidebar, from hover to click

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
Manually triggered a test run with Rodrigo's new poshi changes

**Comment by vicnate5** [comment]
@rodrigo-e-c-souza See results here https://testray.liferay.com/home/-/testray/case_results?testrayRunId=146157168.

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
@clovisdasilvaneto Found a regression on the current version of this pull.

Steps to Reproduce:
1. Create a form
2. Add 2 text fields
3. Go to Rules
4. Add rule (If text1 is equal to value "test", Require text2)
5. Save rule
6. Save form
7. Go to edit rule

**Expected:** Rule can be edited.

**Actual:** Rule cannot be edited and does not display all previously selected values. JS errors thrown. `TypeError: b is undefined`

screenshot 2018-01-09 16 14 01

CC @rodrigo-e-c-souza

**Comment by rodrigo-e-c-souza** [comment]
Thanks @vicnate5 !

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
Retesting with new test fixes.

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by rodrigo-e-c-souza** [comment]
ci:retest

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
@clovisdasilvaneto Please fix the conflicting files. Thx

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by clovisdasilvaneto** [comment]
Hey @rafaprax the conflicts has been solved 👍

**Comment by rodrigo-e-c-souza** [comment]
@rafaprax and @clovisdasilvaneto, feature LGTM, I believe we can merge.

**Comment by rafaprax** [comment]
forward to https://github.com/rafaprax/liferay-portal/pull/257

**Comment by rafaprax** [comment]
ci:close

**Pull request closed without merging**
