### PR TITLE
LPS-74592 Handling for nested fields in the template manager.

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @wanderlast

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
resent at https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/450

**Pull request closed without merging**
