### PR TITLE
LPS-73675 Fix test

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @ctampoya @brunobasto

**Comment by brunobasto** [comment]
Hey @leoadb, looks like the failure is a minor SF error.

**Comment by leoadb** [comment]
ci:retest

**Comment by ctampoya** [comment]
Forms tests disabled in https://github.com/vicnate5/liferay-portal/pull/829

/cc @vicnate5 @leoadb

**Comment by leoadb** [comment]
ci:retest

**Pull request merged**
