### PR TITLE
LPS-77287

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Resent at https://github.com/rafaprax/liferay-portal/pull/262/commits.

**Comment by pedroqueiroz94** [comment]
ci:close

**Pull request closed without merging**
