### PR TITLE
LPS-72251 set request attribute instead of page context attribute since in field renderer we get it from the request

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
Thx @pavel-savinov

**Pull request merged**
