### PR TITLE
LPS-69200 Change the way that the resource bundle for the template handler is retrieved

### PR DESCRIPTION
**Pull request by jkappler**
Hi @marcellustavares, we are working on removing lang merger from journal-web and use capabilities, and we stumbled on an issue when getting the resource bundle through ResourceBundleUtil. 

So we ResourceBundleLoaderUtil instead, which will work in both cases.

Please let us know what you think and if it makes sense. 

Thanks a lot!

cc:// @ealonso

### CODE REVIEW

**Comment by marcellustavares** [comment]
Heeyy @jkappler, are you back to Liferay? :)

**Comment by jkappler** [comment]
Hi @marcellustavares, yes, I'm back :D

**Comment by marcellustavares** [comment]
@jkappler, CI did not triggered for this pull, could you please double check?
 Thanks

**Comment by jkappler** [comment]
ci:retest

**Pull request merged**
