### PR TITLE
LPS-75358 Add condition when the fieldColumnStart doesn't exist

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
@clovisdasilvaneto , there's a source formatting issue. Can you take a look? Thanks!

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
Holding this until https://issues.liferay.com/browse/LRQA-36917 is merged.

**Comment by clovisdasilvaneto** [comment]
Hey @pedroqueiroz94 , can you close this PR? Because I've sent this one in #625

**Pull request closed without merging**
