### PR TITLE
LPS-76307 Do not open select dropdown when clicking on Add or Delete Repeatable button

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by brunobasto** [comment]
LGTM

**Comment by rafaprax** [comment]
ci:retest

**Comment by alinedoleron** [comment]
Pr moved to https://github.com/rafaprax/liferay-portal/pull/248

**Comment by alinedoleron** [comment]
PR moved to https://github.com/rafaprax/liferay-portal/pull/256

**Pull request closed without merging**
