### PR TITLE
LPS-76260 Hide fields only when first condition operand is called, avoiding issues with rendering

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
@leoadb, this should fix the issue that made the Jump to Page poshi test break.

**Comment by leoadb** [comment]
@pedroqueiroz94 Thanks! Let's wait the tests.

**Comment by leoadb** [comment]
@pedroqueiroz94 jump to page issues is fixed, but new ones were thrown. Can you please take a look?

**Comment by rodrigo-e-c-souza** [comment]
LGTM! Some of these tests are already fixed and some are under investigation, anyway they were not caused by this PR.

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Resent at https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/686

**Pull request closed without merging**
