### PR TITLE
LPS-73871

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @fortunatomaldonado @mbowerman

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
@rafaprax , this PR is ok, I just made a small fix in https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/493, so I'm closing this.

cc. @jonathanmccann @fortunatomaldonado @mbowerman

**Comment by pedroqueiroz94** [comment]
ci:close

**Pull request closed without merging**
