### PR TITLE
[TECHNICAL SUPPORT] LPS-76531 The 'ddm-link-to-page' field shows only the first 10 parent/child pages in the radio selector.

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hello,
@antonio-ortega  said I should send directly to this repo, as He already checked it.
The problem comes when you zoom out (with ctrl+mouse wheel) to 67%-80% in the browser. This can result in a decimal "scrollTop" value. In that case the addition of "scrollTop" and "innerHeight" is higher then "scrollHeight" by that decimal amount. Math.trunc() takes care of that problem.
Thank you!

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
LGTM 👍

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Hey @NemethNorbert , I'm getting a javascript console error after applying your fix. :(

Can you take a look at this? Thank you!

screen shot 2017-12-21 at 3 32 02 pm

**Comment by pedroqueiroz94** [comment]
ci:close

**Pull request closed without merging**
