### PR TITLE
master-qa-102

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-31612
https://issues.liferay.com/browse/LPS-68869

cc @vicnate5 @marcellustavares

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by vicnate5** [comment]
@ctampoya Do you know why the test failed here?

**Comment by ctampoya** [comment]
@marcellustavares @leoadb After looking at it a little more, it does look like there is also a regression =( The test that failed asserts that the page you have selected remains selected after exiting out of the iframe. (It covers this bug https://issues.liferay.com/browse/LPS-65726). Follow the steps below to reproduce on the new UI:

1. Add a new page
2. Add a DDL with a Link to Page field
3. Add a DDL Record 
4. Click 'Select' button > Select new page 
5. Click Done
6. Click 'Select' button again to open Link to Page iframe
7. The page you selected on step 4 should still be highlighted 

The only difference between the old and new UI is that instead of asserting the radio is still checked, we need to assert the page is still highlighted.

CC @vicnate5

**Comment by vicnate5** [comment]
@pavel-savinov

**Comment by pavel-savinov** [comment]
@vicnate5 @ctampoya 
I've just pushed missing commit to https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/102

Thanks!

**Pull request closed without merging**
