### PR TITLE
LPS-76079 Reorder parameters

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
@rodrigo-e-c-souza @vicnate5  can you guys check if are there any poshi tests for Select Field with multiple options? Thanks!

**Comment by vicnate5** [comment]
@pedroqueiroz94 We have tests for every field type. Should run here.

**Comment by vicnate5** [comment]
Tests ok. Failures are unrelated.

**Comment by vicnate5** [comment]
We actually do not have a test for this configuration. Adding under https://issues.liferay.com/browse/LRQA-35616

**Comment by vicnate5** [comment]
@pedroqueiroz94 There is an accessibility bug on the Select from List. I cannot confirm if it is from the change here because the field was broken previously.

The `x` button to remove an option is really hard to see.

cannotseeremovalbutton

**Comment by pedroqueiroz94** [comment]
Hey @vicnate5, I think we should treat this in a separate ticket related to lexicon changes, since this is probably broken due to lexicon. What do you think?

**Comment by vicnate5** [comment]
@pedroqueiroz94 That is OK with me. I will file a new ticket.

**Comment by vicnate5** [comment]
Ticket for the issue found in testing https://issues.liferay.com/browse/LPS-76355

**Pull request merged**
