### PR TITLE
LPS-75380 Rename

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@pedroqueiroz94 Please add unit tests for this. Thanks!!

**Comment by rafaprax** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:stop

**Comment by pedroqueiroz94** [comment]
@leoadb, fix to this was submitted in https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/479

**Comment by pedroqueiroz94** [comment]
ci:close

**Pull request closed without merging**
