### PR TITLE
LPS-75830 filtering transient fields

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
resent at https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/713

**Pull request closed without merging**
