### PR TITLE
LPS-71986 Fix tests

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
resent at https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/246

**Pull request closed without merging**
