### PR TITLE
LPS-71986 SF

### PR DESCRIPTION
**Pull request by rafaprax**
Hey @ctampoya,

This pr needs to be merged together with that one in DDL (ctampoya/liferay-portal#114). Probably, it'll be necessary disable some poshi tests until the DDL pr be merged on central repo.

Could you please check these pull requests and disable the needed tests?

Let me know if you have any doubts. Thx 👍

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by ctampoya** [comment]
@rafaprax  Quarantined Forms test here https://github.com/vicnate5/liferay-portal/pull/808

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:stop

**Pull request merged**
