### PR TITLE
LPS-73481 Update references to core version

### PR DESCRIPTION
**Pull request by achaparro**
Hi,

Don't push this pull until this other pull is approved:
https://github.com/brianchandotcom/liferay-portal/pull/50888

Please, update the rest of the repositories in the same way.

Thanks.

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@achaparro What we should do about this PR?

**Comment by achaparro** [comment]
Hi @leoadb,

We can discard it because we finally accept 7.0.0 DTDs in 7.1 version.

Sorry for not warn you before.

Thanks.

**Comment by leoadb** [comment]
@achaparro Thanks!

**Pull request closed without merging**
