### PR TITLE
LPS-76496 Change tag from "aui:fieldset" to "div" in order to keep the same form layout in all browsers

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by brunobasto** [comment]
@alinedoleron Can you check with Rodrigo if we need to update the poshi tests?

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
@leoadb , this PR is tested and reviewed, it should be good to go after the @rodrigo-e-c-souza analyze the tests. :)

**Pull request merged**
