### PR TITLE
LPS-76260 Hide all seconds operands when the rule condition has been changed to a unary condition

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
@leoadb , this is tested and reviewed, it should be good to go after the @rodrigo-e-c-souza analyze the tests.

**Comment by leoadb** [comment]
@alinedoleron @clovisdasilvaneto Could you guys review this one and let me know when it's ok. Thanks!

**Comment by clovisdasilvaneto** [comment]
LGTM!

**Pull request merged**
