### PR TITLE
LPS-71082 Build Lang

### PR DESCRIPTION
**Pull request by diogo-lins**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by thiago-rocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
It seems to be a real failure @diogo-lins. Running the tests again to double check.

**Comment by vicnate5** [comment]
There is a problem with the "Select" fields in Forms. I can take a closer look.

**Comment by vicnate5** [comment]
@diogo-lins @thiago-rocha  There is a regression here. The entries table are not showing any values when the user views entries for a form.

afternoentryvalues

**Also**, The "Select" fields are also not found by the tests, needs a test fix for that.

**Comment by thiago-rocha** [comment]
@vicnate5 this task is still under review with me, so you should wait until a finish the review and assign the JIRA issue to you.

**Comment by vicnate5** [comment]
@thiago-rocha Sounds good!

**Comment by thiago-rocha** [comment]
@vicnate5 now this issue is ready to your review ;)

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
Sent test changes to central
https://github.com/brianchandotcom/liferay-portal/pull/47717

**Comment by vicnate5** [comment]
@thiago-rocha After I fixed the tests, one of the tests found a regression on this pull.

When the user selects an options in the Sidebar > Properties > Autocomplete, the sidebar will automatically close.

#### Steps to Reproduce:
1. Add a data provider
2. Add new form
3. Add Select field
4. Go to Select field sidebar > Properties > Autocomplete
5. Choose a Data Provider

**Expected Result:**
Sidebar remains open so the user can choose an output parameter

**Actual Result:**
Sidebar auto closes upon selecting a data provider.

**Comment by thiago-rocha** [comment]
@diogo-lins could you take a look at what Victor said?

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
Running tests again to confirm the test fixes

**Comment by vicnate5** [comment]
^ Above Test failures are expected due to issue I previously described https://github.com/Liferay/com-liferay-dynamic-data-mapping/pull/70#issuecomment-287908952

**Comment by diogo-lins** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by diogo-lins** [comment]
Resent to https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/92

**Pull request closed without merging**
