### PR TITLE
LPS-72246 Deprecate method

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
When this gets merged a PR should be sent to Journal implementing the new method in order to finish the fix.

**Comment by marcellustavares** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
ci:stop

**Comment by marcellustavares** [comment]
Resent to https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/266

**Pull request closed without merging**
