### PR TITLE
LPS-76177 Add ContentTypes and ServletResponse in doGet method

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by vicnate5** [comment]
Thanks @clovisdasilvaneto, we added some functional tests that should tell us if this issue is still occurring.

**Comment by clovisdasilvaneto** [comment]
Sounds like good @vicnate5 😃

**Comment by vicnate5** [comment]
Test results haven't posted yet, but on the partial results, I can already see the same issue occurring :(

**Comment by clovisdasilvaneto** [comment]
ci:retest

**Pull request closed without merging**
