### PR TITLE
LPS-76911 fixing forms translations

### PR DESCRIPTION
**Pull request by linolaoj**
Hi @vicnate5 , @leoadb ,
I changed some translations but we need the expected values for the other languages. I think other languages can be fixed in other tickets where the reporter will provide the expected translation. What do you think?

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by leoadb** [comment]
@linolaoj I agree. @vicnate5 I'm merging this one, ok? We can't handle the translation to all the languages. Thanks!

**Comment by vicnate5** [comment]
@linolaoj @leoadb Thanks guys. Yea, we can open other tickets to handle other languages. Do you know who we could ask about translation expected values?

**Comment by linolaoj** [comment]
Hi @vicnate5, there is this page on grow https://grow.liferay.com/people/Language+Support, but I'm not sure if those are the people to ask.

**Pull request merged**
