### PR TITLE
LPS-75355 Build lang

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
PR resent at https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/600

**Comment by pedroqueiroz94** [comment]
ci:close

**Pull request closed without merging**
