### PR TITLE
LPS-72849 Update unit tests

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@marcellustavares It look likes the errors are real

**Comment by marcellustavares** [comment]
ci:retest

**Comment by vicnate5** [comment]
@marcellustavares @leoadb This pull fixes a bug with field values. The test is failing because it expects the bugs. Since the forms tests are off right now anyways, you can merge this. Will update the test when we turn it back on.

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRQA-33259

**Pull request merged**
