### PR TITLE
LPS-75355 buildLang

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@vicnate5 Do we have a regression here or we need to update some Poshi test? Thanks!

**Comment by leoadb** [comment]
@vicnate5 It's a regression. I'm looking into it. Thanks!

**Comment by rafaprax** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
@clovisdasilvaneto @alinedoleron 
Could you please check if this pr is updated with the changes requested by the Designer about the remove field feature?
Thx

**Comment by rafaprax** [comment]
Hey guys, there is a conflict here. Please fix it, take a look into my previous message and resend. Thx. @clovisdasilvaneto @alinedoleron

**Pull request closed without merging**
