### PR TITLE
LPS-76085 SF

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
@vicnate5 , can you check these too? Thanks!

**Comment by vicnate5** [comment]
@pedroqueiroz94 Also good. No unique failures. I am looking into the new reoccurring failures.

**Comment by pedroqueiroz94** [comment]
@vicnate5 thanks again for checking this, @vicnate5 ! @rafaprax , can you check if the SF is ok and merge this? Thanks!

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
resent at https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/566

**Pull request closed without merging**
