### PR TITLE
LPS-71082 Set focus in the select after click in a item

### PR DESCRIPTION
**Pull request by diogo-lins**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 Do we need poshi for this one?

**Comment by vicnate5** [comment]
@leoadb There is a way to test this with poshi - Example https://github.com/brianchandotcom/liferay-portal/pull/40831/commits/29d380b1e1dddd9e6c3f2c52aca336c84ea601d3. After thinking about this, I think it would be safer to add a test. It needs to be full end-to-end and check the the reports entry values after submitting.

I can prioritize this pull and writing the test tomorrow.

**Comment by leoadb** [comment]
@vicnate5 Thanks! Please just let me know when you're done.

**Comment by vicnate5** [comment]
@diogo-lins It is confusing to me as a user that I can **only** unselect an option by using the X in the field. I cannot unselect a checkbox.

Could we ask Jadson about this as well?

unselect

**Comment by marcellustavares** [comment]
@leoadb, @vicnate5 has a good point, could you raise an improvement for this story?

Thanks

**Comment by leoadb** [comment]
@marcellustavares Sure!

**Pull request merged**
