### PR TITLE
LPS-73309 Refactoring components radio button an checkbox to Lexicon version 2 

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by leoadb** [comment]
@interaminense Please amend the SF commits with the previous one and push force. Thanks!

**Comment by interaminense** [comment]
Hey @vicnate5,

I was using the fields "Radio button" and "Checkbox" custom of the Clay. [Form elements (custom) on Clay](https://claycss.com/docs/components/form_custom.html)

But since these custom fields still do not cover all cases, I've changed the markups to use the fields default of the Clay. [Form elements on Clay](https://claycss.com/docs/components/form_elements.html)

This way, the "Radio button" and "Checkbox" fields will no longer be hidden.

**Comment by vicnate5** [comment]
Pushed additional test fixes for this https://github.com/brianchandotcom/liferay-portal/pull/52289

**Comment by leoadb** [comment]
ci:retest

**Comment by vicnate5** [comment]
@leoadb This is safe to merge. The remaining test failures are due to the [LPS-72793 Regression](https://issues.liferay.com/browse/LPS-72793?focusedCommentId=1147096&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1147096)

**Comment by leoadb** [comment]
@vicnate5 Thanks!

**Pull request merged**
