### PR TITLE
LPS-73310 Render unfixed elements

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Hey @alinedoleron , can you take a look at the highlight during the search? It's not working anymore. Thank you!

**Comment by pedroqueiroz94** [comment]
I'm closing this, please, send another PR when you're done. @alinedoleron 

Thanks!

**Comment by pedroqueiroz94** [comment]
ci:close

**Pull request closed without merging**
