### PR TITLE
LPS-75116 Add the element property when instantiate FormBuilderFieldOptionsToolbar

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
@vicnate5 is safe to merge this?

**Comment by vicnate5** [comment]
@rafaprax @clovisdasilvaneto There is a problem with the tests that @rodrigo-e-c-souza is fixing right now.

However, there is a unique failure seen on this pull.

*Default Label for the Sidebar*
screenshot 2017-11-17 09 31 24
screenshot 2017-11-17 09 33 31

**Comment by rafaprax** [comment]
@vicnate5 Thx. We'll check that right now.

**Comment by rafaprax** [comment]
Hey, @vicnate5
Did you reproduce the failure caught by`Forms#ViewBlankLabelWhenAddingNewField` locally?

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
@rafaprax I did not reproduce locally. Are you not able to? I can check locally here as well.

**Comment by rafaprax** [comment]
Hey, @vicnate5 I couldn't reproduce it. I'll appreciate your help. Thx 👍

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
Hey, @vicnate5.

I found out the problem.  This assert is no longer necessary `Assert that 'SIDEBAR_HEADER' equals the value 'Unlabeled'` because now we won't show up the text Unlabeled in the add field action. You can check on invision https://liferay.invisionapp.com/share/UDCGITLVR.

So, basically we need just remove\update the `Form#viewSidebarTitle` check.

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRQA-36246

**Comment by rafaprax** [comment]
ci:retest

**Comment by rodrigo-e-c-souza** [comment]
ci:retest

**Comment by vicnate5** [comment]
I aborted the build that Rodrigo triggered, we were just testing his permissions.

**Comment by vicnate5** [comment]
Test Fix sent to central
https://github.com/brianchandotcom/liferay-portal/pull/53152

**Comment by vicnate5** [comment]
@rafaprax This is good. Test fixes for the failures are in Central.

**Comment by rafaprax** [comment]
Thx @vicnate5

**Pull request merged**
