### PR TITLE
LPS-76451 Hide properties tab in paragraph field

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @austinskim123 @mbowerman

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @jonathanmccann please forward this pr to me.

**Comment by rafaprax** [comment]
ci:close

**Comment by pedroqueiroz94** [comment]
Hello, @jonathanmccann . We do not have permissions to merge PRs to subrepos. You can send this to @rafaprax (like he mentioned above) or to me. 

Thanks!

**Comment by jonathanmccann** [comment]
Ah, thank you for letting me know about the change. I'll forward it along on the master branch.

**Comment by austinskim123** [comment]
@jonathanmccann sounds good. Thank you!

**Pull request closed without merging**
