### PR TITLE
LPS-71287 Validate field names during upgrade

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by vicnate5** [comment]
@leoadb I checked this with a 6.1.30 dump I created.

### Results
Upgrade of the ddm module fails with error message
```
ERROR [main][com_liferay_portal_upgrade:97] Invocation to listener threw exception
java.lang.RuntimeException: com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.dynamic.data.mapping.validator.DDMFormValidationException$MustNotDuplicateFieldName: The field name other cannot be defined more than once
```
```
upgrade:check
There is an upgrade process available for com.liferay.dynamic.data.mapping.service from 1.0.0-step-2 to 1.0.3
```

This looks like the correct expected result. My only thought is that the error message could maybe be more specific?
```
The field name "other" from structure ID 10499 cannot be defined more than once
```

Anything else I can check?

**Comment by leoadb** [comment]
@vicnate5 Done! Thanks a lot!

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@rafaprax Can you approve and merge this one? Thanks!

**Pull request merged**
