### PR TITLE
LPS-70561 SF

### PR DESCRIPTION
**Pull request by thiago-rocha**

### CODE REVIEW

**Comment by thiago-rocha** [comment]
@brunobasto please take a look at this pr

**Comment by brunobasto** [comment]
@thiago-rocha, I've sent you a boilerplate for tests to the module you changed: https://github.com/thiago-rocha/com-liferay-dynamic-data-mapping/pull/1

The only thing that stroke me as odd, was that we are calling `.validatePage()` both from https://github.com/brunobasto/com-liferay-dynamic-data-mapping/blob/LPS-70561/dynamic-data-mapping-form-renderer/src/main/resources/META-INF/resources/js/form_pagination_support.js#L110

and 

https://github.com/brunobasto/com-liferay-dynamic-data-mapping/blob/LPS-70561/dynamic-data-mapping-form-renderer/src/main/resources/META-INF/resources/js/form_pagination_support.js#L269

Is there a chance that `.validatePage()` will be called twice and two requests will be sent to the server?

**Comment by thiago-rocha** [comment]
@diogo-lins

**Comment by leoadb** [comment]
ci:retest

**Comment by diogo-lins** [comment]
ci:retest

**Pull request merged**
