### PR TITLE
LPS-70895 Declare poshi toggle for changing parameter labels of data provider

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@pedroqueiroz94, I didn't quite get this yet. why path in the input?

**Comment by pedroqueiroz94** [comment]
@marcellustavares hey, it was just to keep consistency with the name of the output, but I changed the label at the user view

**Comment by marcellustavares** [comment]
got it @pedroqueiroz94, I'll merge this pull to mine. Thanks

**Comment by vicnate5** [comment]
@pedroqueiroz94 @marcellustavares See https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/101

**Comment by marcellustavares** [comment]
thx @vicnate5

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:close

**Pull request closed without merging**
