### PR TITLE
LPS-71453 Make CI fail when JavaScript tests fail

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
@vicnate5 Not sure why this is failing. Do you have an idea?

**Comment by vicnate5** [comment]
There is an error being thrown at head on the portal log. Since the integration tests starts master, it catches the error. This isn't related to your pull.
```
19:11:12,634 ERROR [Framework Event Dispatcher: Equinox Container: c024b309-fc0f-0017-1f1b-a1d9b94939a1][com_liferay_frontend_js_loader_modules_extender:97] FrameworkEvent ERROR 
     [exec] java.lang.NullPointerException
```

**Comment by brunobasto** [comment]
Got it. Thanks, Victor!

**Comment by marcellustavares** [comment]
Super cool, thx @brunobasto!

**Comment by marcellustavares** [comment]
rebase issues @brunobasto, could you please resend? Thanks

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
@marcellustavares, rebased

**Comment by leoadb** [comment]
@brunobasto I've experienced some errors like that. Usually I send a new pull request and tests pass. I'm closing this one, could you please send a new one?

**Pull request closed without merging**
