### PR TITLE
LPS-75159 Copy staged model data handler classes

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
This PR fixes the issue found on https://github.com/liferay/liferay-portal/pull/2326

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by rafaprax** [comment]
Thx @pedroqueiroz94

**Comment by pedroqueiroz94** [comment]
hey @vicnate5 , can you please check why this did not trigger a central repo PR for this fix? Thank you!

**Comment by vicnate5** [comment]
@pedroqueiroz94 The request is too old for me to easily find the cause on the server. Will look for trigger on the next merge.

**Pull request merged**
