### PR TITLE
LPS-71421 Add test

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@thiago-rocha or @diogo-lins Could you please review the frontend code? This is not the complete implementation for the story in question. There is other subtask filled in Jira.

**Comment by leoadb** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Thanks @leoadb, please try to merge the remaining task before the release. This is a nice thing to have.

**Comment by leoadb** [comment]
@marcellustavares Will need help from the frontend guys. I'll talk to them. Thanks.

**Pull request merged**
