### PR TITLE
LPS-73309 Refactoring components radio button an checkbox to Lexicon version 2

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:retest

**Comment by interaminense** [comment]
ci:retest

**Comment by leoadb** [comment]
@vicnate5 We have real Poshi errors here. We've changed some styles to be compatible with new lexicon pattern. We've replaced **help-block** with **form-feedback-indicator**. Messages.macro is referencing the old class. I'm afraid we cannot change that macro because other teams might not did the changes yet. What can we do? Thanks!

**Comment by vicnate5** [comment]
@leoadb We can use an "or" statement with the locator. 

Track here https://issues.liferay.com/browse/LRQA-35502

**Comment by vicnate5** [comment]
@interaminense The input for the radio field appears offscreen due to this change.

In order for me to input the field with the functional test, I have to click a hidden element. Is there anything we can do about this behavior?

#### --When inputting field, the `<input>` is hidden:
inputentry

#### --When viewing entries, the user can see the problem on the screen:
viewentry

**Comment by vicnate5** [comment]
Fix for field error message here: https://github.com/brianchandotcom/liferay-portal/pull/52244

The other failures are due to the hidden input field and mismatched input display.

**Comment by leoadb** [comment]
ci:retest

**Comment by interaminense** [comment]
forwarded to https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/460

**Pull request closed without merging**
