### PR TITLE
LPS-71571 Add poshi toggle

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
@leoadb the poshi toggle in https://github.com/leoadb/liferay-portal/pull/356 should be merged first in order for this PR to pass.

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
resent at https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/285

**Pull request closed without merging**
