### PR TITLE
LPS-71856 The default toolbarSet is always being used rather than the toolbarSet related to the WYSIWYG editor specified in portal.properties

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @dustinryerson

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by leoadb** [comment]
@dustinryerson I have a fix for that in https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/197

**Comment by dustinryerson** [comment]
@leoadb thank you for the information

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by dustinryerson** [comment]
@leoadb any updates on this?

**Comment by leoadb** [comment]
@dustinryerson We are waiting for this PR to come in https://github.com/brianchandotcom/liferay-portal/pull/49122 . Some tests were temporarily disabled and this PR enables them.

**Comment by dustinryerson** [comment]
@leoadb sounds good, thank you!

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Pull request merged**
