### PR TITLE
LPS-76501 Fall back to LocaleUtil

### PR DESCRIPTION
**Pull request by IstvanD**
Hello,

This is an additional commit for LPS-76501 to fix the breaking tests.
https://github.com/liferay/liferay-portal/pull/2509#issuecomment-356431011

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
Sent to https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/670

**Pull request closed without merging**
