### PR TITLE
LPS-71378 Create data provider endpoint

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 @marcellustavares DDM part

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@vicnate5

**Comment by vicnate5** [comment]
@leoadb It is just the forms tests failing. That is good news. Can we merge this and trigger merge to central?

**Comment by leoadb** [comment]
@vicnate5 Yeah @marcellustavares will do that

**Pull request merged**
