### PR TITLE
LPS-75830 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by rafaprax** [comment]
Hey @jeyvison, Could you please take a look at this? Thx

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Hey @rafaprax , @jeyvison , I'm going to resend this to liferay-portal.
Thanks!

**Comment by jeyvison** [comment]
No need Lino. Already sent this one to @rafaprax

**Comment by rafaprax** [comment]
already sent to https://github.com/rafaprax/liferay-portal/pull/247

**Pull request closed without merging**
