### PR TITLE
LPS-73520 check if formBuilderTab exist

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
@leoadb , @rafaprax this is good to go!

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
sent to https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/712

**Pull request closed without merging**
