### PR TITLE
LPS-75338 Create independent sortable lists

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi,

Can you review this PR, please?

You can find further information in LPS-75338.

Thanks,

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by antonio-ortega** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by antonio-ortega** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by antonio-ortega** [comment]
Hi @leoadb , 

Did you have the chance to have a look at this PR? Please don't hesitate to ask me any question about it.

Thanks!

**Comment by leoadb** [comment]
@pedroqueiroz94 Could you please help me out to review this PR? Thanks!!

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
@leoadb , tested and approved. :)

**Comment by leoadb** [comment]
@pedroqueiroz94 Thanks!!

**Comment by JavierMoral** [comment]
Hi @leoadb @pedroqueiroz94,
Thanks for the review!
It seems that tests failed in the subrepo-pull-request and the code didn't get merged in master. If I try to see the details I get a 404.
Could you please take a look at this?

**Pull request merged**
