### PR TITLE
LPS-73331 Order DDMStructure Fields in descending parental order

### PR DESCRIPTION
**Pull request by natocesarrego**
cc @gregory-bretall

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by natocesarrego** [comment]
Hey @leoadb and @rafaprax,

The error reported by CI is not related with the change made on this pull, I've already checked Jenkins.

Thanks.

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Pull request merged**
