### PR TITLE
LPS-74861 Build lang

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 This is the one I mentioned we need to update Poshi. We've moved field type modal to a sidebar. Thanks!

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRQA-35336

**Comment by leoadb** [comment]
@vicnate5 Should I merge or wait until you guys get the changes done?

**Comment by vicnate5** [comment]
@leoadb Will do the change right now. Because the tests will turn back on with https://github.com/brianchandotcom/liferay-portal/pull/52013, need to fix first.

**Comment by leoadb** [comment]
@vicnate5 ok Thanks!

**Comment by vicnate5** [comment]
Fix send to central
https://github.com/brianchandotcom/liferay-portal/pull/52059

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@vicnate5 Is it ok? Thanks!

**Comment by ctampoya** [comment]
@leoadb Tests will be fixed under LRQA-35365 
/cc @vicnate5

**Pull request merged**
