### PR TITLE
LPS-71093 revert 42bf353ceece2923798440c0552f99b0aacc5207 since we do not need these changes anymore

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@jpince @pyoo47 are we having issues with subrepo PR tests? Thanks

**Comment by jpince** [comment]
@marcellustavares there was a build issue at head that should have been resolved by [ec403af](https://github.com/liferay/liferay-portal/commit/ec403af0923e1baff2614a6cb29f930dc77b303c)

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@marcellustavares @pavel-savinov can't tell if this is related to your pull or not, error message isn't really that helpful
```
     [exec] Execution failed for task ':apps:forms-and-workflow:dynamic-data-mapping:dynamic-data-mapping-type-grid:checkSourceFormatting'.
```

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Pull request merged**
