### PR TITLE
LPS-68869 format selected layout breadcrumb on server side instead of javascript code

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Retesting to double check if it's a real failure, cc @pavel-savinov

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@pavel-savinov, it seems we have a real failure, could you please double check?

See https://testray.liferay.com/reports/production/logs/test-1-21/1490465238330/test-subrepository-acceptance-pullrequest(master)/41/subrepository-functional-tomcat80-mysql56-jdk8/2/0/CPDynamicdatalists_AddListRecordWithLinkToPageField/summary.html.gz

Thanks

**Comment by pavel-savinov** [comment]
@marcellustavares Yes, it is. The test should be changed since the UX is different now. Who is in charge of it?

**Comment by marcellustavares** [comment]
Hi @vicnate5 @ctampoya, could you take a look at @pavel-savinov 's pull?

Thanks

**Comment by vicnate5** [comment]
@marcellustavares We can take a look at this. Will need to update the tests and add a toggle for the new test changes.

**Comment by ctampoya** [comment]
Pushed sub-repo with toggle file https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/131

**Comment by leoadb** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
@vicnate5 @ctampoya Could you please take care of it? I've added fix for highlighting of selected element.

**Comment by ctampoya** [comment]
@pavel-savinov Yes, I will send in a fix for that =)

**Comment by vicnate5** [comment]
Test fix pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/48189

@ctampoya Can you resend this subreop pull with the toggle?

**Comment by ctampoya** [comment]
Resent subrepo pull with toggle https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/160

**Pull request closed without merging**
