### PR TITLE
LPS-68869 Add toggle to toggle file

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Resent from https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/160

@rafaprax Please take a look(and if you consider it is necessary, run performance tests). We have exactly the same layout item selector used in 3+ places in portal and it never caused performance regression. The main idea is that it should be consistent across the portal, right now DDM is the only place where we still have the old one.

cc @ealonso @leoadb

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by martaeli** [comment]
@rafaprax we were hoping you could take a look at @pavel-savinov's PR. Thanks!

**Comment by rafaprax** [comment]
@martaeli We have a problem in this PR and I've already point it in the previous PR https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/160#issuecomment-296644284. I agree that the UI should be consistent across the portal but we can't lose performance. You can take a look at this thread to understand the problem (https://in.liferay.com/web/support/forums/-/message_boards/message/18188126).

@pavel-savinov Could you please apply the UI changes without lose the improvements about perfomance?

For now I'm going to close this PR.

Thanks

\cc @leoadb @marcellustavares

**Pull request closed without merging**
