### PR TITLE
LPS-74728 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
@rafaprax, this PR seems good! :)

**Comment by rafaprax** [comment]
Thx @pedroqueiroz94

**Pull request merged**
