### PR TITLE
ddm-ct-102

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LPS-68869

cc @vicnate5 @leoadb @pavel-savinov

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by vicnate5** [comment]
@ctampoya Only 1 `<toggles>` tag can exist. You need to add the `<toggle>` inside.

**Comment by ctampoya** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@vicnate5, @ctampoya, I'm getting failures on the Forms#SubmitFormContainingCaptchaAndViewTextFieldValue test in other pulls, is it a new regression or a flaky test?

Thanks

**Comment by ctampoya** [comment]
@marcellustavares The test failure is a new regression [LPS-71828](https://issues.liferay.com/browse/LPS-71828).

**Comment by ctampoya** [comment]
ci:retest

**Comment by ctampoya** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Thanks @ctampoya. @leoadb how this regression was introduced?

**Comment by marcellustavares** [comment]
Maybe it was external to our code. Changes in the taglib or something. We need to investigate

**Comment by vicnate5** [comment]
@marcellustavares @leoadb 

We are pretty sure it was introduced by changes in this pull: https://github.com/brianchandotcom/liferay-portal/pull/48177

**Comment by rafaprax** [comment]
@pavel-savinov This pr is removing code related to a performance improve that we did in the link-to-page field. Basically the performance issue happens when a site has a bunch of pages and the field loading take a lot of time to finish. Could you please fix that scenario and resend this changes?

FYI, the performance improvements were made under this ticket https://issues.liferay.com/browse/LPS-65726

Thx and sorry for the delay

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
