### PR TITLE
LPS-75160 - Fixed to older browser versions

### PR DESCRIPTION
**Pull request by harlanbruno**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
@rafaprax , this seems good to go :)

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Closing this, check changes in https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/521

**Comment by pedroqueiroz94** [comment]
ci:close

**Pull request closed without merging**
