### PR TITLE
LPS-71717 Field name generation based on the field label should be disabled if there're content associated to the structure

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by marcellustavares** [comment]
This seems to be a real failure, will take a look at it.

**Comment by joshuacords** [comment]
@marcellustavares, do you have an idea how long the fix will take?

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Retesting at https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/176

**Pull request closed without merging**
