### PR TITLE
LPS-71173 Auto SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@jpince, weird error on this pull :(

**Comment by marcellustavares** [comment]
ci:retest

**Comment by jpince** [comment]
@pyoo47 @michaelhashimoto thoughts on the above? "Unable to generate test report."

**Comment by pyoo47** [comment]
@jpince This is a tough one.. I don't see much information in the console logs that indicates what went wrong. I suspect that it may have been a fluke jenkins failure to respond to a rest API call to get some json data but it's hard to say for sure.

**Comment by jpince** [comment]
@pyoo47 thanks, will wait for the next result

**Comment by leoadb** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:stop

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Sorry Leo, didn't see your retest before.

**Comment by leoadb** [comment]
👍  :)

**Comment by marcellustavares** [comment]
Finally! could you check my changes and merge this in @leoadb? Thanks

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@leoadb, I've pushed the fix.

**Comment by marcellustavares** [comment]
ci:stop

**Comment by marcellustavares** [comment]
ci:retest

**Pull request merged**
