### PR TITLE
LPS-70395 SF

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
Hey @pedroqueiroz94, we recently updated the subrepo PR tester and are encountering some issues. We'll look into it this and try to get it fixed asap! Sorry for the inconvenience!

**Comment by kenjiheigel** [comment]
I'm going to test a fix on this pull and trigger a retest.

**Comment by pedroqueiroz94** [comment]
alright, @kenjiheigel , thanks!

**Comment by kenjiheigel** [comment]
@pedroqueiroz94, looks like it should be working now. The fix has been merged upstream to the liferay-jenkins-ee repo.

**Comment by pedroqueiroz94** [comment]
@kenjiheigel , thank you for this! :)

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Pull request merged**
