### PR TITLE
LPS-72743 Attach drag and drop plugins

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by JosemariaMunoz** [comment]
Hey @leoad,

I tried this code but It didn't work for me, maybe I'm doing something wrong...
Did it work for you according to this test [issue-dragging-repeatable-field-web-content.gif](https://issues.liferay.com/secure/attachment/216982/issue-dragging-repeatable-field-web-content.gif)?

Thanks!

**Comment by leoadb** [comment]
@JosemariaMunoz it worked for me. I'm going to try it again.

**Comment by leoadb** [comment]
ci:retest

**Comment by JosemariaMunoz** [comment]
Sorry @leoadb, I only try to help, It works horizontally but not if I drag down with a repeatable field and scrolling down at the same time (inside the popup).
Did you try again and work well?
Thank you!

**Comment by leoadb** [comment]
@josemariamunoz it didn't work. :( I'm investigating the issue again. Thanks!!

**Comment by JosemariaMunoz** [comment]
Ok @leoadb, no problem, thanks to you!

**Comment by JosemariaMunoz** [comment]
Hey @leoadb,

Finally, Did you find a solution?

Thanks!

**Pull request closed without merging**
