### PR TITLE
LPS-76531 Fix for regression caused by original fix. 

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi,

I copy [Norbert's explanation](https://github.com/antonio-ortega/com-liferay-dynamic-data-mapping/pull/3#issue-287079393) about this issue:

> Now with the check of "(scrollHeight - (scrollTop + innerHeight) <= 1)" the render request can tiger twice with fast scrolling.
With oldStart we check if it wants to render the same data twice, when the users scrolls down fast.
I use the same ticket number for the regression fix, because the LPS-76531 hasn`t been backported yet.
Thanks

/cc @NemethNorbert

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
Hi, @antonio-ortega , we have a SF issue. Can you take a look at this? Thank you!

**Comment by antonio-ortega** [comment]
ci:test

**Comment by antonio-ortega** [comment]
ci:retest

**Comment by antonio-ortega** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Resent at https://github.com/rafaprax/liferay-portal/pull/260

**Comment by pedroqueiroz94** [comment]
ci:close

**Pull request closed without merging**
