### PR TITLE
LPS-76143 Put the error message in the end of formGroup

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by matuzalemsteles** [comment]
LGTM!

**Comment by interaminense** [comment]
LGTM!

**Comment by brunobasto** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by alinedoleron** [comment]
Moved to https://github.com/rafaprax/liferay-portal/pull/261

**Pull request closed without merging**
