### PR TITLE
LPS-75354 Sort css properties, remove dubble call of _createFieldActions, apply formatSource

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rodrigo-e-c-souza** [comment]
ci:retest

**Comment by rodrigo-e-c-souza** [comment]
ci:retest

**Comment by rodrigo-e-c-souza** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rodrigo-e-c-souza** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rodrigo-e-c-souza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
@rodrigo-e-c-souza Test fix here https://github.com/brianchandotcom/liferay-portal/pull/53158

**Pull request merged**
