### PR TITLE
LPS-74997 Bump package version

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
This should be testable by using a Poshi Test. The poshi test can follow the steps to reproduce in the description of [LPS-74997](https://issues.liferay.com/browse/LPS-74997).

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
Sent to https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/462

**Pull request closed without merging**
