### PR TITLE
LPS-77319 Use putWithoutReplicator() to avoid nodes from clearing eac…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…h other without updates.

### CODE REVIEW

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/54605.

**Comment by pedroqueiroz94** [comment]
ci:close

**Pull request closed without merging**
