### PR TITLE
LPS-76260 Refactoring the function to hide all seconds operands when the rule condition has been changed to a unary condition

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:stop

**Comment by leoadb** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
PR resent at https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/631

**Comment by pedroqueiroz94** [comment]
ci:close

**Pull request closed without merging**
