### PR TITLE
LPS-75159 Bump package version

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 This is the PR we talked about yesterday. Could you help us to manually test this? You'll need to disable the old portlet in order to test a published form. Let us know if you need anything. Thanks!!!

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRQA-35725

**Comment by rafaprax** [comment]
ci:retest

**Comment by vicnate5** [comment]
@rafaprax compile failure?

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Pull request closed without merging**
