### PR TITLE
LPS-76083 adding error message to parent node

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by linolaoj** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by linolaoj** [comment]
Hi, going to resend to liferay-portal.

**Comment by linolaoj** [comment]
Here it is https://github.com/pedroqueiroz94/liferay-portal/pull/41

**Pull request closed without merging**
