### PR TITLE
LPS-76141 Always changing the title, not only when the showback icon is displayed

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
hey @vicnate5 , are these poshi failures related to the PR? Thanks!

**Comment by vicnate5** [comment]
@pedroqueiroz94 Failures not related to this pull.

**Comment by pedroqueiroz94** [comment]
thanks, @vicnate5 ! @rafaprax , this seems good to go. :)

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
