### PR TITLE
LPS-71082 SF Multiple Select

### PR DESCRIPTION
**Pull request by diogo-lins**

### CODE REVIEW

**Comment by leoadb** [comment]
@diogo-lins This seems to be a real error. The select with the options "Value" and "Other Field" is not shown when the operator is selected.

**Comment by diogo-lins** [comment]
@leoadb I found the bug, I need to change something in the portal repo, How we proceed with this one? You merge this and I send another PR in the portal repo?

**Comment by leoadb** [comment]
ci:retest

**Comment by diogo-lins** [comment]
@leoadb all tests passed o/

**Comment by leoadb** [comment]
@diogo-lins Thanks!

**Pull request merged**
