### PR TITLE
LPS-72999

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay,

Attached is an update for http://issues.liferay.com/browse/LPS-72999.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by rafaprax** [comment]
@pedroqueiroz94 Could you please check this fix? Thx

**Comment by jonmak08** [comment]
This was a backport from https://github.com/liferay/com-liferay-dynamic-data-mapping/commit/8a4d7560e27e48ee878697b4de65668e6835687e

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
For some reason the error message is not shown in the CI comment:

```
[echo] :apps:forms-and-workflow:dynamic-data-mapping:dynamic-data-mapping-test:compileTestJava FAILED
     [echo] 
     [echo] BUILD FAILED
     [echo] 
     [echo] Total time: 42.52 secs
     [echo] Gradle build finished at 2017-11-15 02:19:58.976.
     [echo] Note: /opt/dev/projects/github/liferay-portal-7.0.x/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-form-renderer/src/test/java/com/liferay/dynamic/data/mapping/form/renderer/internal/DDMFormLayoutTransformerTest.java uses unchecked or unsafe operations.
     [echo] Note: Recompile with -Xlint:unchecked for details.
     [echo] /opt/dev/projects/github/liferay-portal-7.0.x/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-test/src/test/java/com/liferay/dynamic/data/mapping/type/select/SelectDDMFormFieldValueAccessorTest.java:20: error: package com.liferay.portal.json does not exist
     [echo] import com.liferay.portal.json.JSONFactoryImpl;
     [echo]                               ^
```

Is the subrepo now managing the 7.0.x version of the DDM code?

**Comment by rafaprax** [comment]
Exactly @vicnate. The subrepos don't manage the 7.0.x version. Thx to see this detail. I did not see that this pr was send to 7.0.x branch.

Hey @jonmak08 the subrepo only manage the master branch. So, backport should be send to the liferay-portal/7.0.x branch. Thx

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/liferay/liferay-portal-ee/pull/3306

**Pull request closed without merging**
