### PR TITLE
LPS-73479

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by yuhai** [comment]
Hi team,

Please refer to the related portal fix from https://github.com/matethurzo/liferay-portal/pull/1702.

Explanation: https://github.com/hhuijser/com-liferay-dynamic-data-mapping/pull/4

Regards,
Hai

**Comment by leoadb** [comment]
@pedroqueiroz94 Could you please review this one? If it's ok, please let me know, so I can approve.

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by leoadb** [comment]
ci:retest

**Pull request merged**
