### PR TITLE
LPS-76762 Use a value accessor to retrieve value for localized fields

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz94** [comment]
PR resent at https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/686.

**Comment by pedroqueiroz94** [comment]
ci:close

**Pull request closed without merging**
