### PR TITLE
LPS-75159 Fix test

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
hey @vicnate5 , we're having some test failures related to com/liferay/petra/xml/XMLUtil. Do you have any idea if anybody is taking a look at this? Thank you!

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by tomwang2011** [comment]
@pedroqueiroz94 @vicnate5 @jpince I think we located the cause, CI is forcing the latest version of Util-java that contains the petra-xml change, eventhough your module's build.gradle is asking for 2.0.0 version. We are testing a solution to not force the latest version now, thanks!

**Comment by pedroqueiroz94** [comment]
Hello, @tomwang2011 , thanks for checking that! Is there anything we need to change? Or you guys are manage this all? Thank you again!

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
hi @tomwang2011 , do you have any news on that issue? Thank you!

**Comment by tomwang2011** [comment]
hi Pedro, the fix is committed at https://github.com/brianchandotcom/liferay-portal/pull/53798, once CI start to pick up portal built after that change this issue should be resolved, thanks!

**Comment by pedroqueiroz94** [comment]
thank you, @tomwang2011

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by tomwang2011** [comment]
Hi Pedro, once https://issues.liferay.com/browse/LRQA-36904 gets merged, the petra modules should deploy correctly and the petra-xml issue should disappear, thanks!

**Comment by pedroqueiroz94** [comment]
Thank you for the heads up, @tomwang2011. 
We really appreciate! :)

**Pull request closed without merging**
