### PR TITLE
LPS-72621 Update tests

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by vicnate5** [comment]
Hey @rafaprax,

If found an issue in testing that is preventing me from fixing the tests.

The Data Provider does load paginated, but it does not load the full index. The user cannot search for "United States" until the user manually scrolls down to the last page. Only the first page values are available in the field search.

This also affects Autocomplete. The autocomplete will only have the values of the "first page" results from the data provider.

There is still a fix needed on the test, I will work on this in while you take a look.

**Comment by rafaprax** [comment]
OK @vicnate5 , we'll take a look into that case. Thx

**Pull request closed without merging**
