### PR TITLE
LPS-75495 Avoid function override, instead, apply evaluation to text field instance

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
@vicnate5 these tests are failing due to CI, I guess... I tried those locally and I could not reproduce :/  Can you check that, please?

**Comment by vicnate5** [comment]
@pedroqueiroz94 After this change, our tests have trouble inputting values into the input fields. I tried to use a workaround that worked for some of them, but not all.

I cannot reproduce manually either, but when the test tries to type into the field, only the first 2 characters get entered. I noticed that the field sends a POST request on every character entered, there could be an issue because our tests can type faster than humans. Is there anything we can do to improve the responsiveness of the text fields? This is not an issue we have with any other fields in portal.

Example failure:
failuretoentertext

**Comment by pedroqueiroz94** [comment]
@vicnate5 , good catch. It wasn't supposed to send a lot of requests, we noticed the debouncer is not working with this fix. Thanks!

**Pull request closed without merging**
