### PR TITLE
LPS-72793 Normalize key

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@vicnate5 @rafaprax This should fix the regression we have

**Comment by vicnate5** [comment]
Expected behavior of the Field Options names looks to have changed. https://issues.liferay.com/browse/LRQA-35623

**Comment by vicnate5** [comment]
@leoadb @rafaprax 

The behavior changes to always regen the field name when editing the Option field.

I am worried about the affects the change of the field name will have on other parts of the form.

Here is an example. I changed the Label for an option that is used in a rule. The new name breaks the form rule.
optioneditissue

**Comment by leoadb** [comment]
@vicnate5 I’m working to fix that. Thanks!!

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
@vicnate5 Don't know why this is failing

**Pull request merged**
