### PR TITLE
LPS-73343 Using bad portlet id in dynamic-data-mapping/dynamic-data-mapping-taglib module

### PR DESCRIPTION
**Pull request by dustinryerson**
https://issues.liferay.com/browse/LPS-73343

### CODE REVIEW

**Comment by natocesarrego** [comment]
Hi @dustinryerson,

Did you cc me on this pull just for me be aware of this change?

Thanks.

**Comment by dustinryerson** [comment]
@natocesarrego yes that's why. I realized after I sent it here that I should have sent it to you first, but it had already been merged.

**Comment by natocesarrego** [comment]
Ok, @dustinryerson. Thanks for that! 😉

**Pull request merged**
