### PR TITLE
LPS-75936 Create empty edit page to fix RequestDispatcher NPE

### PR DESCRIPTION
**Pull request by pedroqueiroz94**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
@rodrigo-e-c-souza, can you please investigate this?

**Comment by rodrigo-e-c-souza** [comment]
@pedroqueiroz94 These bugs are know, so they are not related to this PR:
FormsUpgrade#AddFormAfterUpgrade621015
Forms#SubmitForm3x3Layout
Forms#SubmitFormWithMultipleFieldsAndViewEntriesViaDescriptiveDisplay
FormRules#ConfigureCalculateRule
FormRules#ConfigureRequireRule
FormRules#EditRule
Forms#Add20Forms
Forms#Add30Fields

But, the one affecting these cases is new, it is probably related to the PR:

Forms#SubmitFormContainingCaptchaAndViewTextFieldValue 
FormRules#UseIsNotEmptyRuleToShowField
Forms#SelectAndRemoveMultipleOptionsInSelectFromListField
Forms#SubmitWithRequiredDateField
Forms#ViewFieldValidationIsNotBypassedWhenNextButtonIsHitTwice
FormsJumpToPage#ViewPagesAfterJump

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by topolik** [comment]
Hi guys,

here is a NPE:
https://testray.liferay.com/reports/production/logs/test-1-7/1513874072041/test-subrepository-acceptance-pullrequest(master)/162/subrepository-functional-tomcat80-mysql56-jdk8/12/0/jenkins-console.txt.gz 

That is fixed in https://github.com/brianchandotcom/liferay-portal/pull/53845 - "LPS-75936 Fix classloading issue b2abab0". You need portal to have this commit for the tests to pass.

**Comment by pedroqueiroz94** [comment]
We will wait for it to be merged in order to retest. Thanks for the heads up, @topolik !

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
This has been merged on central, so we sent this https://github.com/brianchandotcom/liferay-portal/pull/54108 to kill DDL there.

**Pull request merged**
