### PR TITLE
LPS-71932 Use typed response, instead of the auto conversion. This will prevent returning output response values that does not correspond with the configured output type.

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by vicnate5** [comment]
@marcellustavares Won't this make it more difficult for the end-user to create a data provider? How will the user know the syntax?

**Comment by marcellustavares** [comment]
@vicnate5, we need to improve the ux ideally. By now what we can do is to link the JSONPath syntax in our docs.

**Comment by marcellustavares** [comment]
I agree with you the UX is not very good for non tech users.

**Comment by vicnate5** [comment]
CC @rbohl

**Comment by vicnate5** [comment]
CC @rbohl

**Comment by rbohl** [comment]
Thanks for cc'ing me, @vicnate5 . I'll probably need to track this in a LRDOCS ticket. After a quick look at the changes to DDMRestDataProvider.java, I don't understand what the syntax changes are for users configuring a data provider in the UI.

**Comment by vicnate5** [comment]
@rbohl See the ticket comments https://issues.liferay.com/browse/LPS-71932.

**Pull request merged**
